# Generated by Django 4.2.5 on 2023-11-07 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('entreprise_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_commercial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rest_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrat_status', models.CharField(choices=[('P', 'Pending'), ('S', 'signed')], default='P', max_length=1)),
                ('client_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_client', to='core.client')),
                ('gestion_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_gestion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_contact', models.TextField()),
                ('event_date_start', models.DateTimeField()),
                ('event_date_end', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('attendees', models.IntegerField()),
                ('notes', models.TextField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_client', to='core.client')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_commercial', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_contract', to='core.contract')),
                ('gestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_gestion', to=settings.AUTH_USER_MODEL)),
                ('support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_support', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
