# Generated by Django 3.2.5 on 2024-03-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date_start',
            field=models.DateField(),
        ),
    ]
